### ISSUE TITLE
LUA error on login

### ISSUE THREAD

**Issue by Manu224781** [RavenousAddons/ravTodo#1]
Heya, the addon cannot be opened.

`1x ravTodo/functions.lua:108: bad argument #1 to 'IsQuestFlaggedCompleted' (outside of expected range -2147483648 to 2147483647 - Usage: local isCompleted = C_QuestLog.IsQuestFlaggedCompleted(questID))
[string "=[C]"]: in function `IsQuestFlaggedCompleted'
[string "@ravTodo/functions.lua"]:108: in function <ravTodo/functions.lua:101>
[string "@ravTodo/functions.lua"]:200: in function <ravTodo/functions.lua:196>
[string "@ravTodo/functions.lua"]:363: in function `CacheAndBuild'
[string "@ravTodo/core.lua"]:24: in function <ravTodo/core.lua:18>

Locals:
(*temporary) = "Commander Ral'esh"
(*temporary) = "outside of expected range -2147483648 to 2147483647 - Usage: local isCompleted = C_QuestLog.IsQuestFlaggedCompleted(questID)"`

**Comment by Manu224781** [comment]
Edit: When I disable Silverdragon it works. Hope that helps.

**Comment by waldenp0nd** [comment]
Hey @Theni224, thanks for the feedback.

I believe I've fixed this in [the latest release, 0.0.8](https://github.com/RavenousAddons/ravTodo/releases/tag/0.0.8). It looks like the error came from a piece of debugging that I stupidly forgot to remove before pushing the update. Let me know if the new version solves your issue! 🤞

**Comment by Manu224781** [comment]
Working like a charm now. Keep up the great work!
