### ISSUE TITLE
Feature request: LDB

### ISSUE THREAD

**Issue by Manu224781** [RavenousAddons/ravTodo#2]
Not a bug, but a feature request:

Add LDB compatibility so we can add it to databars on ElvUI or Titan Panel.

Attached is an example of another addon.

Thanks!

![8f89a7ad1f46a637a83a72880dafa7e4](https://github.com/RavenousAddons/ravTodo/assets/126989436/1a91dd09-b54d-4292-a212-26cbcbbaf452)

**Comment by waldenp0nd** [comment]
I'll have to do some more research into this one before I can make an educated call on this feature.

**Comment by waldenp0nd** [comment]
Hey @Theni224,

I've made some progress on this. Still working out how best to display the data and not bloat things too much for non-users of of databars. That being said, the [latest version, 0.1.0](https://github.com/RavenousAddons/ravTodo/releases/tag/0.1.0) contains some preliminary functionality towards getting this working.

Hopefully this suffices for at least the time being!

**Comment by Manu224781** [comment]
Wow sweet! That works quite nicely. Now I don't have to type /todo every time I want to open it. Keep up the good work!

**Comment by waldenp0nd** [comment]
Going to close this as we've got LDB in there now, so further LDB-related feature-requests and bugs can be captured in new issues.
